spring.application.name=BackGestion

# ── Conexion a Base de Datos (PostgreSQL colegio) ─────────────────
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/colegio}
spring.datasource.username=${DB_USERNAME:posgrade}
spring.datasource.password=${DB_PASSWORD:PossGAdmin}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ─────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Puerto del servidor ─────────────────────────────────────────
server.port=8080

# ── Swagger / SpringDoc ─────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
