name: CI Build Check

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build
      
      - name: Subir por FTP a cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/frontend/browser/
          server-dir: /public_html/
          port: 21            # <-- Fuerza el puerto de FTP clásico
          security: loose     # <-- Desactiva TLS/SSL si tu FileZilla es FTP plano

